# Generated by Django 5.2.7 on 2025-11-19 14:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash / Petty Cash'), ('FASTAG', 'Fastag Wallet'), ('DIESELCARD', 'Diesel Card Wallet')], default='BANK', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Driver ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('wage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_trip_expense', models.BooleanField(default=True, verbose_name='Related to Trip Cost (P&L)')),
            ],
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('TRANSPORTER', 'Transporter (Hired Carrier)'), ('WORKSHOP', 'Workshop / Service Vendor'), ('CLIENT', 'Client / Consignor'), ('OTHER', 'Other Vendor')], default='OTHER', max_length=20, verbose_name='Party Type (Role)')),
                ('name', models.CharField(max_length=100, verbose_name='Company/Vendor Name')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN/Tax ID')),
                ('bank_account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Commission %')),
                ('orai_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Orai Fixed Charge')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Vehicle Number')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('ownership', models.CharField(default='Own', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hypothecation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hypothecation Details')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('fitness_expiry', models.DateField(blank=True, null=True, verbose_name='Fitness Expiry')),
                ('permit_expiry', models.DateField(blank=True, null=True, verbose_name='Permit Expiry')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry')),
                ('national_permit', models.CharField(blank=True, max_length=50, null=True)),
                ('puc_expiry', models.DateField(blank=True, null=True, verbose_name='PUC Expiry')),
                ('tax_expiry', models.DateField(blank=True, null=True, verbose_name='Tax Expiry')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('shop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Workshop Location/Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Bill Amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.expensecategory')),
                ('paid_via_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_payments', to='management.accountmaster', verbose_name='Paid From Account')),
                ('workshop', models.ForeignKey(limit_choices_to={'party_type__in': ['WORKSHOP', 'OTHER']}, on_delete=django.db.models.deletion.PROTECT, to='management.partymaster', verbose_name='Workshop/Vendor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, editable=False, max_length=15, unique=True, verbose_name='Trip ID')),
                ('date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('orai_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('halting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In-transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('client', models.ForeignKey(limit_choices_to={'party_type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_client', to='management.partymaster', verbose_name='Client (Consignor)')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.driver')),
                ('transporter', models.ForeignKey(limit_choices_to={'party_type': 'TRANSPORTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_transporter', to='management.partymaster', verbose_name='Transporter (Carrier)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DocketTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('docket_no', models.CharField(max_length=50, unique=True)),
                ('send_date', models.DateField(verbose_name='Docket Sent Date')),
                ('challan_received', models.BooleanField(default=False, verbose_name='Challan/Docket Received')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Received Date')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.driver')),
                ('transporter', models.ForeignKey(limit_choices_to={'party_type': 'TRANSPORTER'}, on_delete=django.db.models.deletion.PROTECT, to='management.partymaster')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.expensecategory')),
                ('paid_via_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.accountmaster', verbose_name='Paid Via Account')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.trip')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='management.accountmaster', verbose_name='From Account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='management.accountmaster', verbose_name='To Account (For Transfers/Deposits)')),
                ('related_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.maintenanceexpense', verbose_name='Related Maintenance Payment')),
                ('related_maintenance_expense', models.ForeignKey(blank=True, help_text='Links to the source Maintenance Expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from_maintenance', to='management.maintenanceexpense')),
                ('related_trip', models.ForeignKey(blank=True, help_text='Links to the source Trip (e.g., for receipts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from_trip', to='management.trip')),
                ('related_trip_expense', models.ForeignKey(blank=True, help_text='Links to the source Trip Expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from_trip_expense', to='management.tripexpense')),
            ],
        ),
    ]
